Add blogpost for project 2019
ElixirCourse/blog pull request #40
Opened 2019-05-24 21:57 UTC by IvanIvanoff

2019-05-24 21:59 UTC, Reductions requested changes

2019-05-24 21:59 UTC, Reductions commented on posts/news/project_2019.md
> +- Домашни - 30 точки
45 точки

2019-05-24 21:59 UTC, Reductions commented on posts/news/project_2019.md
> +Максималният възможен брой точки е 110 (без да броим бонус точките, давани за активно участие в лекциите).
125

2019-05-25 05:37 UTC, meddle0x53 approved these changes
На мен ми изглежда добре, само да оправим това дето Слави казва.

2019-05-25 05:41 UTC, meddle0x53 commented
@Reductions оправих го

2019-05-27 08:26 UTC, merged